// <auto-generated />
using System;
using DeveloperCore.WoodRoute.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperCore.WoodRoute.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703130608_AddIamModel")]
    partial class AddIamModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Engagement.Domain.Model.Aggregates.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_stage");

                    b.Property<DateTimeOffset?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_delivery_date");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("PublicTrackingId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_tracking_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_conversations");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("i_x_conversations_order_id");

                    b.HasIndex("PublicTrackingId")
                        .IsUnique()
                        .HasDatabaseName("i_x_conversations_public_tracking_id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Engagement.Domain.Model.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender_type");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_messages");

                    b.HasIndex("ConversationId", "SentAt")
                        .HasDatabaseName("i_x_messages_conversation_id_sent_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Inventory.Domain.Model.Aggregates.InventoryMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("MinStock")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_stock");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_inventory_materials");

                    b.ToTable("inventory_materials");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Manufacturing.Domain.Model.Aggregates.ManufactureOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarpenterId")
                        .HasColumnType("integer")
                        .HasColumnName("carpenter_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_order_id");

                    b.Property<bool>("StagesAreDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("stages_are_defined");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_manufacture_orders");

                    b.HasIndex("SalesOrderId")
                        .IsUnique()
                        .HasDatabaseName("i_x_manufacture_orders_sales_order_id");

                    b.ToTable("manufacture_orders", (string)null);
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Manufacturing.Domain.Model.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedTimeInDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_time_in_days");

                    b.Property<int>("ManufactureOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("manufacture_order_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_stages");

                    b.HasIndex("ManufactureOrderId")
                        .HasDatabaseName("i_x_stages_manufacture_order_id");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarpenterId")
                        .HasColumnType("integer")
                        .HasColumnName("carpenter_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PublicTrackingId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_tracking_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_orders");

                    b.HasIndex("PublicTrackingId")
                        .IsUnique()
                        .HasDatabaseName("i_x_orders_public_tracking_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("ReceiptReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receipt_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_payments_order_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedProductionDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_production_days");

                    b.Property<decimal>("LaborCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("labor_cost");

                    b.Property<decimal>("MaterialsCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("materials_cost");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_quotes");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("i_x_quotes_order_id");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Engagement.Domain.Model.Entities.Message", b =>
                {
                    b.HasOne("DeveloperCore.WoodRoute.Platform.Engagement.Domain.Model.Aggregates.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_messages_conversations_conversation_id");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Manufacturing.Domain.Model.Entities.Stage", b =>
                {
                    b.HasOne("DeveloperCore.WoodRoute.Platform.Manufacturing.Domain.Model.Aggregates.ManufactureOrder", null)
                        .WithMany("Stages")
                        .HasForeignKey("ManufactureOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_stages_manufacture_orders_manufacture_order_id");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("DeveloperCore.WoodRoute.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email_address");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.HasIndex("Address")
                                .IsUnique()
                                .HasDatabaseName("i_x_profiles_email_address");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("DeveloperCore.WoodRoute.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", b =>
                {
                    b.OwnsOne("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.ValueObjects.FurnitureDetails", "Details", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Depth")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("depth");

                            b1.Property<string>("DesignNotes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("design_notes");

                            b1.Property<string>("FurnitureType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("furniture_type");

                            b1.Property<decimal>("Height")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("height");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("material");

                            b1.Property<decimal>("Width")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("width");

                            b1.HasKey("Id")
                                .HasName("p_k_orders");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_orders_orders_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Payment", b =>
                {
                    b.HasOne("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_orders_order_id");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Quote", b =>
                {
                    b.HasOne("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", null)
                        .WithOne("Quote")
                        .HasForeignKey("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Quote", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_quotes_orders_order_id");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Engagement.Domain.Model.Aggregates.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Manufacturing.Domain.Model.Aggregates.ManufactureOrder", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Quote");
                });
#pragma warning restore 612, 618
        }
    }
}
