// <auto-generated />
using System;
using DeveloperCore.WoodRoute.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeveloperCore.WoodRoute.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarpenterId")
                        .HasColumnType("integer")
                        .HasColumnName("carpenter_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PublicTrackingId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_tracking_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_orders");

                    b.HasIndex("PublicTrackingId")
                        .IsUnique()
                        .HasDatabaseName("i_x_orders_public_tracking_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("ReceiptReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receipt_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_payments_order_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedProductionDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_production_days");

                    b.Property<decimal>("LaborCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("labor_cost");

                    b.Property<decimal>("MaterialsCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("materials_cost");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_quotes");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("i_x_quotes_order_id");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", b =>
                {
                    b.OwnsOne("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.ValueObjects.FurnitureDetails", "Details", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Depth")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("depth");

                            b1.Property<string>("DesignNotes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("design_notes");

                            b1.Property<string>("FurnitureType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("furniture_type");

                            b1.Property<decimal>("Height")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("height");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("material");

                            b1.Property<decimal>("Width")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("width");

                            b1.HasKey("Id")
                                .HasName("p_k_orders");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_orders_orders_id");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Payment", b =>
                {
                    b.HasOne("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_orders_order_id");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Quote", b =>
                {
                    b.HasOne("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", null)
                        .WithOne("Quote")
                        .HasForeignKey("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Entities.Quote", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_quotes_orders_order_id");
                });

            modelBuilder.Entity("DeveloperCore.WoodRoute.Platform.Sales.Domain.Model.Aggregates.Order", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Quote");
                });
#pragma warning restore 612, 618
        }
    }
}
